package com.mds.manager.model;

public class RoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_user.id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_user.user_id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_user.role_id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_user.id
     *
     * @return the value of t_role_user.id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_user.id
     *
     * @param id the value for t_role_user.id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_user.user_id
     *
     * @return the value of t_role_user.user_id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_user.user_id
     *
     * @param userId the value for t_role_user.user_id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_user.role_id
     *
     * @return the value of t_role_user.role_id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_user.role_id
     *
     * @param roleId the value for t_role_user.role_id
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}